version: 0.1

environment_variables:
  plaintext:
    HUGO_VERSION: "0.111.1"
    
phases:
  install:
    commands:                                                                 
      - cd /tmp
      - wget https://github.com/gohugoio/hugo/releases/download/v0.111.1/hugo_0.111.1_Linux-64bit.tar.gz
      - tar -xzf hugo_0.111.1_Linux-64bit.tar.gz
      - mv hugo /usr/bin/hugo
      - cd 
      - rm -rf /tmp/*
  build:
    commands:
      - rm -rf public
      - hugo 
  post_build:
    commands:

      - echo Build completed on `date`
 